func result() ! {
    raise Error("simple error");
}

func result2() ! {
    raise Error("simple error (raised: {}, idx: {})", true, 0);
}

func main() {
    result() catch |err| {
        assert!(err.msg() == "simple error".to_string());
    };

    result2() catch |err2| {
        assert!(err2.msg() == "simple error (raised: true, idx: 0)".to_string());
    };
}
